<?php
/**
 *
 * Author: Dieter Beelaert
 *
 */

/* Hook called on every request
 * This will check if the user requests an rdf file, if so the module will kick in and try to get the right format
 */
function mmlabRdf_init(){
    $path = parse_url(current_path());
    $path = $path['path'];
    if(preg_match('/\.ttl|\.jsonld|\.rdf|\.nt|\.n3/i',$path)){
       mmlabRdf_getRdf($path);
    }
}

function mmlabRdf_getRdf($path){
    $suffix = explode('.',$path)[0];

    $uri = 'http://' . $_SERVER['HTTP_HOST'] . base_path() . '?q=' . $suffix;
    $format = getFormat($path);
    if (easyrdf()) {
        $graph = new EasyRdf_Graph($uri);
        $graph->load($uri,'guess');
        $content_type = EasyRdf_Format::getFormat($format);
        header('Content-type :'. $content_type->getDefaultMimeType());
        print $graph->serialise($format);
        //stop rendering html output
        die;
    }else{
        drupal_set_message('easyRDF API is not installed correctly');
    }
}

function getFormat($path){
    $split = explode('.',$path);
    switch($split[1]){
        case 'ttl':return 'turtle';
        break;
        case 'jsonld': return 'json';
        break;
        case 'rdf': return 'rdfxml';
        break;
        case 'nt': return 'ntriples';
        break;
        case 'n3': return 'n3';
        break;
    }
}



//create custom page which renders rdf data,

